// frontend-vue/src/app/App.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';

const users = ref<any[]>();

const fetchData = async () => {
  const response = await fetch('http://localhost:5152/users');
  const data = await response.json();
  users.value = data;
};

onMounted(() => {
  fetchData();
});
</script>

<template>
  <v-data-table :items="users"> </v-data-table>
</template>

// frontend/src/app/app.tsx
import { useEffect, useState } from "react"
import styled from "styled-components"

const StyledApp = styled.div`
  // Your style here
`

export function App() {
  const [data, setData] = useState<any>()

  const fetchData = async () => {
    const response = await fetch("http://localhost:5152/users")
    const data = await response.json()
    setData(data)
  }

  useEffect(() => {
    fetchData()
  }, [])

  return <StyledApp>{JSON.stringify(data)}</StyledApp>
}

export default App
